apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodContainerImages
metadata:
  name: podcontainerimages
spec:
  match:
    kinds:
    - apiGroups:
      - apps
      - ""
      kinds:
      - DaemonSet
      - Deployment
      - StatefulSet
      - Pod
